/**
 * positions.js — random starting positions for practice.
 *
 * Two generators, because the two phases want opposite techniques:
 *
 *   - ENDGAMES are generated procedurally. A handful of material templates
 *     (K+P vs K, rook endings, opposite bishops…) are scattered onto the board
 *     and then *validated by the engine itself* — no rules are reimplemented
 *     here. Anything illegal or already decided is thrown away and retried.
 *     Scattering works because endgames are sparse: almost any legal
 *     arrangement of a rook and two pawns is a plausible study.
 *
 *   - MIDGAMES are generated by letting the engine play a semi-random opening
 *     against itself. Scattering fails here — twenty pieces dropped at random
 *     make a position no game could ever reach, which teaches nothing — so we
 *     pay for a few shallow searches and get a coherent game instead.
 *
 * Everything is driven by a seeded PRNG, so a seed reproduces a position
 * exactly. That makes the fuzz tests deterministic.
 */

import {
  WHITE,
  BLACK,
  opposite,
  initialBoard,
  initialContext,
  EMPTY_CONTEXT,
  applyMove,
  nextContext,
  legalMoves,
  getGameStatus,
  inCheck,
  findKing,
  evaluate,
  bestMove,
} from "./engine.js";

/** mulberry32 — tiny, fast, seedable. Returns a function giving [0, 1). */
export function makeRng(seed) {
  let a = seed >>> 0;
  return function rng() {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const randInt = (rng, n) => Math.floor(rng() * n);
const pick = (rng, list) => list[randInt(rng, list.length)];

/**
 * Endgame material templates, written as a **strong** and a **weak** side
 * rather than White and Black.
 *
 * That split is what makes all three difficulties reachable from one table:
 * the player is handed the strong side to convert a win, the weak side to
 * defend, and a `level` template when the position should be equal. (Writing
 * these as white/black instead quietly makes "defend" impossible, because
 * every study is drawn from the winning side's point of view.)
 *
 * `verify` is an optional extra condition for templates whose label makes a
 * promise a random scatter wouldn't keep.
 */
export const ENDGAME_TEMPLATES = [
  // Lopsided — one side is clearly better.
  { id: "kp-k", label: "King and pawn vs king", strong: ["p"], weak: [] },
  { id: "two-pawns", label: "Two pawns vs one", strong: ["p", "p"], weak: ["p"] },
  { id: "rp-r", label: "Rook and pawn vs rook", strong: ["r", "p"], weak: ["r"] },
  { id: "q-vs-p", label: "Queen vs advanced pawn", strong: ["q"], weak: ["p"] },
  { id: "rook-vs-minor", label: "Rook vs minor piece", strong: ["r", "p"], weak: ["n", "p"] },
  { id: "minor-vs-pawns", label: "Minor piece vs pawns", strong: ["b"], weak: ["p", "p"] },
  { id: "extra-exchange", label: "The exchange up", strong: ["r", "p", "p"], weak: ["b", "p", "p"] },

  // Level — same material on both sides.
  { id: "rook-ending", label: "Rook ending", strong: ["r", "p", "p"], weak: ["r", "p", "p"], level: true },
  { id: "pawn-ending", label: "Pawn ending", strong: ["p", "p", "p"], weak: ["p", "p", "p"], level: true },
  { id: "knight-ending", label: "Knight ending", strong: ["n", "p", "p"], weak: ["n", "p", "p"], level: true },
  {
    id: "opp-bishops",
    label: "Opposite-coloured bishops",
    strong: ["b", "p", "p"],
    weak: ["b", "p", "p"],
    level: true,
    // The label promises opposite colours, so enforce it rather than hope.
    verify: (board) => {
      const squares = [];
      for (let r = 0; r < 8; r++) {
        for (let c = 0; c < 8; c++) if (board[r][c][1] === "b") squares.push((r + c) % 2);
      }
      return squares.length === 2 && squares[0] !== squares[1];
    },
  },
];

/**
 * How far from equal a position must be to count as each difficulty, in
 * centipawns from the *player's* point of view.
 */
const BANDS = {
  balanced: { min: -120, max: 120 },
  convert: { min: 250, max: 1400 },
  defend: { min: -1400, max: -250 },
};

/** The three difficulty keys, for callers that want to choose at random. */
export const DIFFICULTIES = Object.keys(BANDS);

const TARGETS = {
  balanced: "Equal position — outplay them",
  convert: "You're winning — convert it",
  defend: "You're worse — hold the draw",
};

/**
 * Is this a sane position to hand a player? Delegates every rule question to
 * the engine, so the generator can never drift from the real move rules.
 */
export function isPlayable(board, turn, ctx = EMPTY_CONTEXT) {
  const wk = findKing(board, WHITE);
  const bk = findKing(board, BLACK);
  if (!wk || !bk) return false;
  // Kings may never stand next to each other.
  if (Math.max(Math.abs(wk.r - bk.r), Math.abs(wk.c - bk.c)) < 2) return false;
  // Pawns cannot exist on the promotion ranks.
  for (let c = 0; c < 8; c++) {
    if (board[0][c][1] === "p" || board[7][c][1] === "p") return false;
  }
  // The side that just "moved" cannot have left its own king in check.
  if (inCheck(board, opposite(turn))) return false;
  // And the game must still be alive for the player to move.
  return getGameStatus(board, turn, ctx) === "playing";
}

/** All empty squares, so pieces can be placed without collisions. */
function emptySquares(board) {
  const free = [];
  for (let r = 0; r < 8; r++) {
    for (let c = 0; c < 8; c++) if (!board[r][c]) free.push([r, c]);
  }
  return free;
}

function place(board, rng, piece) {
  const isPawn = piece[1] === "p";
  const free = emptySquares(board).filter(([r]) => !isPawn || (r > 0 && r < 7));
  if (free.length === 0) return false;
  const [r, c] = pick(rng, free);
  board[r][c] = piece;
  return true;
}

/**
 * One attempt at a position for `template`. `strongColor` decides which side
 * gets the better half of the template. Returns null if the scatter landed
 * somewhere illegal — the caller simply tries again.
 */
function tryEndgame(rng, template, strongColor) {
  const board = Array.from({ length: 8 }, () => Array(8).fill(""));
  const weakColor = opposite(strongColor);
  // Kings first: they constrain everything else.
  if (!place(board, rng, strongColor + "k")) return null;
  if (!place(board, rng, weakColor + "k")) return null;
  for (const t of template.strong) if (!place(board, rng, strongColor + t)) return null;
  for (const t of template.weak) if (!place(board, rng, weakColor + t)) return null;
  return board;
}

/**
 * A random endgame for `playerColor` (who is always to move).
 * Falls back to a guaranteed-legal K+P vs K position if the sampler is
 * unlucky, so this can never hang or return something unplayable.
 */
export function generateEndgame(rng, { difficulty = "balanced", playerColor = WHITE } = {}) {
  const band = BANDS[difficulty] || BANDS.balanced;
  // Balanced play wants level material; the other two want a lopsided study,
  // handed to the player from the winning or losing side accordingly.
  const level = difficulty === "balanced";
  const templates = ENDGAME_TEMPLATES.filter((t) => Boolean(t.level) === level);
  const strongColor = difficulty === "defend" ? opposite(playerColor) : playerColor;

  for (let attempt = 0; attempt < 400; attempt++) {
    const template = pick(rng, templates);
    const board = tryEndgame(rng, template, strongColor);
    if (!board) continue;
    if (!isPlayable(board, playerColor, EMPTY_CONTEXT)) continue;
    if (template.verify && !template.verify(board)) continue;
    // evaluate() is from White's perspective; flip it for a Black player.
    const edge = playerColor === WHITE ? evaluate(board) : -evaluate(board);
    if (edge < band.min || edge > band.max) continue;
    return {
      board,
      ctx: EMPTY_CONTEXT,
      turn: playerColor,
      label: template.label,
      target: TARGETS[difficulty] || TARGETS.balanced,
      phase: "endgame",
    };
  }
  return fallbackEndgame(playerColor, difficulty);
}

/** A hand-built position used only if rejection sampling runs out of tries. */
function fallbackEndgame(playerColor, difficulty) {
  const board = Array.from({ length: 8 }, () => Array(8).fill(""));
  const other = opposite(playerColor);
  board[7][1] = playerColor + "k";
  board[4][3] = playerColor + "p";
  board[0][4] = other + "k";
  return {
    board,
    ctx: EMPTY_CONTEXT,
    turn: playerColor,
    label: "King and pawn vs king",
    target: TARGETS[difficulty] || TARGETS.balanced,
    phase: "endgame",
  };
}

/**
 * A random middlegame, reached by playing a real opening.
 *
 * Each move is drawn from the engine's top candidates rather than always the
 * best one — the same trick the worker uses to make low levels human — so the
 * openings vary instead of replaying one line every time.
 */
export function generateMidgame(
  rng,
  { difficulty = "balanced", playerColor = WHITE, plies = 16, depth = 2 } = {}
) {
  const band = BANDS[difficulty] || BANDS.balanced;

  for (let attempt = 0; attempt < 6; attempt++) {
    let board = initialBoard();
    let ctx = initialContext();
    let color = WHITE;
    let ok = true;

    for (let i = 0; i < plies; i++) {
      const result = bestMove(board, color, depth, ctx);
      if (!result.move) { ok = false; break; }
      // Any candidate within a pawn of the best keeps the game sensible while
      // still branching; early moves wander more, later ones tighten up.
      const best = result.candidates[0].score;
      const window = i < 6 ? 120 : 60;
      const near = result.candidates.filter((cand) => Math.abs(cand.score - best) <= window);
      const chosen = pick(rng, near.length ? near : result.candidates);
      board = applyMove(board, chosen.move);
      ctx = nextContext(ctx, chosen.move);
      color = opposite(color);
    }
    if (!ok) continue;

    // Hand over with the player to move.
    if (color !== playerColor) {
      const result = bestMove(board, color, depth, ctx);
      if (!result.move) continue;
      board = applyMove(board, result.move);
      ctx = nextContext(ctx, result.move);
    }
    if (!isPlayable(board, playerColor, ctx)) continue;

    const edge = playerColor === WHITE ? evaluate(board) : -evaluate(board);
    // Self-play rarely produces a lopsided game, so the winning/losing bands
    // are treated as a preference here rather than a hard requirement — a
    // near-equal middlegame is still a perfectly good thing to practise.
    const inBand = edge >= band.min && edge <= band.max;
    if (!inBand && attempt < 3) continue;

    return {
      board,
      ctx,
      turn: playerColor,
      label: "Middlegame — find a plan",
      target: inBand ? TARGETS[difficulty] || TARGETS.balanced : TARGETS.balanced,
      phase: "midgame",
    };
  }

  // Every attempt fell through: give them the opening rather than nothing.
  return {
    board: initialBoard(),
    ctx: initialContext(),
    turn: playerColor,
    label: "Standard opening",
    target: TARGETS.balanced,
    phase: "midgame",
  };
}

/** Dispatch used by the worker. */
export function generatePosition({ phase, difficulty, playerColor, seed }) {
  const rng = makeRng(seed >>> 0);
  return phase === "midgame"
    ? generateMidgame(rng, { difficulty, playerColor })
    : generateEndgame(rng, { difficulty, playerColor });
}
